SET IDENTITY_INSERT [dbo].[Courses] ON
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (1, 1, N'course_1.svg', N'Fullstack Web Developer Course from Scratch', N'Robert Fox', N'$12.50', NULL, N'220', N'94%', N'4.2k')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (2, 0, N'course_2.svg', N'HTML, CSS, JavaScript Web Developer', N'Jenny Wilson & Marvin McKinney', N'$15.99', NULL, N'160', N'92%', N'3.1k')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (3, 0, N'course_3.svg', N'The Complete Front-End Web Development Course', N'Albert Flores', N'$44.99', N'$9.99', N'100', N'98%', N'2.7k')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (4, 0, N'course_4.svg', N'iOS & Swift - The Complete iOS App Development Course', N'Marvin McKinney', N'$15.99', NULL, N'160', N'92%', N'3.1k')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (5, 1, N'course_5.svg', N'Data Science & Machine Learning with Python', N'Esther Howard', N'$11.20', NULL, N'160', N'92%', N'3.1k')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (6, 0, N'course_6.svg', N'Creative CSS Drawing Course: Make Art With CSS', N'Robert Fox', N'$10.50', NULL, N'220', N'94%', N'4.2k')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (7, 0, N'course_7.svg', N'Blender Character Creator v2.0 for Video Games Design', N'Ralph Edwards', N'$18.99', NULL, N'160', N'92%', N'3.1k')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (8, 0, N'course_8.svg', N'The Ultimate Guide to 2D Mobile Game Development with Unity', N'Albert Flores', N'$44.99', N'$12.99', N'100', N'98%', N'3.1k')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (9, 0, N'course_9.svg', N'Learn JMETER from Scratch on Live Apps-Performance Testing', N'Jenny Wilson', N'$14.50', NULL, N'160', N'92%', N'3.1k')
SET IDENTITY_INSERT [dbo].[Courses] OFF

